stages:
    - build
    - deploy
variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    GIT_SUBMODULE_STRATEGY: recursive

build:
    stage: build
    image: docker:19.03.8
    services:
        - docker:19.03.8-dind
    before_script:
        - docker info
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    tags:
        - dind
    script:
        - docker pull $CI_REGISTRY_IMAGE:latest || true
        - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker push $CI_REGISTRY_IMAGE:latest
deploy:
    stage: deploy
    image: alpine:latest
    script:
        - apk update
        - apk add openssh
        - chmod a-rwx "$DEPLOY_KEY"
        - chmod u+rw "$DEPLOY_KEY"
        - ssh -o StrictHostKeyChecking=no $DEPLOY_SSH_URI -i $DEPLOY_KEY "docker-direct pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
        - ssh -o StrictHostKeyChecking=no $DEPLOY_SSH_URI -i $DEPLOY_KEY "docker-direct tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA dokku/desobot:$CI_COMMIT_SHA"
        - ssh -o StrictHostKeyChecking=no $DEPLOY_SSH_URI -i $DEPLOY_KEY "tags:deploy desobot $CI_COMMIT_SHA"