apiVersion: v1
kind: Secret
metadata:
  name: desobot-discord
stringData:
  token: bot_token_here
  id: client_id_here
  secret: api_secret_here
  errorLogChannel: error_log_channel_here
---
apiVersion: v1
kind: Secret
metadata:
  name: desobot-mysql
stringData:
  connstr: 'Server=mariadb;Database=desobot;User=desobot;Password=desobot'
  # used if using included mysql.yml to create a db service. make sure these match `connstr`
  rootPass: root
  database: desobot
  user: desobot
  password: desobot